services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./backend:/app

  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - ./backend/.env
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgres/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

volumes:
  pgdata:
  node_modules:


